goal: null
planner_source: openai
planner_model: o3-mini-2025-01-31
#planner_source: ollama
#planner_model: qwen3:1.7b
#planner_source: cesnet
#planner_model: deepseek-r1
summarizing: false
summarizer_source: openai
summarizer_model: gpt-4o-2024-08-06
#interpreter_source: ollama
#interpreter_model: qwen3:1.7b
interpreter_source: openai
interpreter_model: gpt-3.5-turbo
action_limit: 50
targets:
  ubuntu:
    host: localhost
    port: 2222
    user: root
    password: 'y54325342'
  shellm:
    host: localhost
    port: 22
    user: admin
    password: admin
default_target: ubuntu
llm_providers:
  openai:
    kind: openai
  ollama:
    kind: ollama
    host: localhost
    port: 11434
  cesnet:
    kind: openai
    base_url: https://chat.ai.e-infra.cz/api
    api_key_env: CESNET_API_KEY
